# Generated by Django 5.1.2 on 2025-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsession',
            name='token_no',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
    ]
