# Generated by Django 5.1.2 on 2025-03-08 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsession',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
