# Generated by Django 5.1.2 on 2025-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0002_pollsession_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsession',
            name='counter_token',
            field=models.IntegerField(default=0),
        ),
    ]
