# Generated by Django 5.1.2 on 2025-03-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0003_pollsession_counter_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollsession',
            old_name='counter_token',
            new_name='used_token_count',
        ),
    ]
