# Generated by Django 5.1.2 on 2025-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0004_rename_counter_token_pollsession_used_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsession',
            name='counter_token',
            field=models.IntegerField(default=0),
        ),
    ]
