# Generated by Django 5.1.2 on 2025-03-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0005_pollsession_counter_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollsession',
            name='counter_token',
        ),
    ]
