# Generated by Django 5.1.2 on 2025-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0006_remove_pollsession_counter_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsession',
            name='counter_token',
            field=models.IntegerField(default=0),
        ),
    ]
