# Generated by Django 5.1.2 on 2025-03-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokencast', '0007_pollsession_counter_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvote',
            name='vote',
        ),
    ]
