# Generated by Django 5.1.2 on 2024-11-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=1991, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='emp_id',
            field=models.CharField(default='2024-11-22', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
