# Generated by Django 5.1.2 on 2024-11-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_email_teacher_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
