# Generated by Django 5.1.2 on 2024-11-24 17:57

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='year_completed',
        ),
        migrations.AddField(
            model_name='qualification',
            name='award_doc',
            field=models.ImageField(blank=True, null=True, upload_to=teachers.models.get_image_path, verbose_name='Upload Award Letters'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='dt_award',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Award'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='thesis',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title of Dissertation/Thesis'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree/Certificate'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of University/Institute'),
        ),
    ]
