# Generated by Django 5.1.2 on 2024-11-24 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_remove_qualification_year_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qualification',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
