# Generated by Django 5.1.2 on 2024-11-26 07:13

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_qualification_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='award_doc',
            field=models.ImageField(blank=True, null=True, upload_to=teachers.models.get_quali_path, verbose_name='Upload Award Letters'),
        ),
    ]
