# Generated by Django 5.1.2 on 2024-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_alter_qualification_award_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='award_doc',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Award Letters'),
        ),
    ]
