# Generated by Django 5.1.2 on 2024-11-26 12:43

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_alter_qualification_award_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='award_doc',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.get_quali_path, verbose_name='Upload Award Letters'),
        ),
    ]
