# Generated by Django 5.1.2 on 2024-11-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_alter_qualification_award_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
