# Generated by Django 5.1.2 on 2024-11-27 11:52

import django.db.models.deletion
import django.utils.timezone
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_alter_qualification_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('', 'Select Status'), ('stat-1', 'Published'), ('stat-2', 'Granted')], max_length=10, null=True, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title of the Patent')),
                ('ref_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Document No./Patent No./Other reference no')),
                ('dt_award', models.DateField(blank=True, null=True, verbose_name='Publication/Award Date')),
                ('awarding_agency', models.CharField(blank=True, max_length=200, null=True, verbose_name='Patent Awarding Agency')),
                ('patent_ecopy', models.FileField(blank=True, null=True, upload_to=teachers.models.get_quali_path, verbose_name='Upload e-copy of the patent')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
