# Generated by Django 5.1.2 on 2024-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_patents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patents',
            options={'verbose_name': 'Patent', 'verbose_name_plural': 'Patents'},
        ),
        migrations.AddField(
            model_name='patents',
            name='dept_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
