# Generated by Django 5.1.2 on 2024-11-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_alter_patents_options_patents_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='dept_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
