# Generated by Django 5.1.2 on 2024-11-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_qualification_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='prog_cd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
