# Generated by Django 5.1.2 on 2024-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_department_prog_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=255, verbose_name='Title of Paper')),
                ('name_of_authors', models.CharField(max_length=255, verbose_name='Name of the Author(s)')),
                ('name_of_journal', models.CharField(max_length=255, verbose_name='Name of Journal')),
                ('year_of_publication', models.CharField(max_length=4, verbose_name='Year of Publication')),
                ('issn_number', models.CharField(max_length=50, verbose_name='ISSN Number')),
                ('journal_website', models.CharField(max_length=500, verbose_name='Link to Website of the Journal')),
                ('article_website', models.CharField(max_length=500, verbose_name='Link to Website of Article/Paper/Abstract')),
                ('is_listed_in_ugc_care', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is it Listed in UGC Care List')),
            ],
        ),
    ]
