# Generated by Django 5.1.2 on 2024-11-30 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_researchpub'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpub',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='researchpub',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
