# Generated by Django 5.1.2 on 2025-02-28 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=10, unique=True)),
                ('short_name', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('OPERATOR', 'Operator'), ('INSPECTOR', 'Inspector')], max_length=50)),
                ('full_name', models.CharField(choices=[('System Administrator', 'System Administrator'), ('Production Manager', 'Production Manager'), ('Quality Supervisor', 'Quality Supervisor'), ('Machine Operator', 'Machine Operator'), ('Quality Inspector', 'Quality Inspector')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fpr', models.CharField(max_length=255, verbose_name='First Person Responsible')),
                ('target_dt', models.CharField(max_length=50, verbose_name='Target Date')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.useraccess')),
            ],
        ),
    ]
