# Generated by Django 5.1.2 on 2025-03-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingsession',
            old_name='faculty_id',
            new_name='faculty',
        ),
    ]
