# Generated by Django 5.1.2 on 2025-03-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_accessid_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('access_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.accessid')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.votingsession')),
            ],
        ),
    ]
