# Generated by Django 5.1.2 on 2025-06-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrcApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='PartyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('BILL_TO', 'Bill To'), ('SHIP_TO', 'Ship To')], max_length=10)),
                ('party_code', models.CharField(max_length=20)),
                ('party_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_details', to='nrcApp.customer')),
            ],
        ),
    ]
