# Generated by Django 5.1.2 on 2025-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrcApp', '0002_alter_customer_address_partydetail'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partydetail',
            constraint=models.UniqueConstraint(fields=('customer', 'party_type'), name='unique_customer_partytype'),
        ),
    ]
