# Generated by Django 5.1.2 on 2025-06-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrcApp', '0003_partydetail_unique_customer_partytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partydetail',
            name='party_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
