# Generated by Django 5.1.2 on 2025-07-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrcApp', '0004_alter_partydetail_party_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('belt_type', models.CharField(choices=[('Steel Cord', 'Steel Cord'), ('Fabric', 'Fabric')], max_length=50)),
                ('width_mm', models.PositiveIntegerField(help_text='Width in millimeters')),
                ('thickness_mm', models.DecimalField(decimal_places=2, help_text='Total thickness in mm', max_digits=5)),
                ('tensile_strength', models.CharField(help_text='e.g., ST1000, ST1250', max_length=50)),
                ('cover_grade', models.CharField(help_text='e.g., M24, DIN X', max_length=50)),
                ('construction', models.TextField(help_text='Description of construction and specifications')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price in INR or USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrcApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='nrcApp.invoice')),
            ],
        ),
    ]
