# Generated by Django 5.1.2 on 2025-07-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrcApp', '0005_productmaster_invoice_productline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to_party',
            field=models.ForeignKey(blank=True, limit_choices_to={'party_type': 'BILL_TO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_invoices', to='nrcApp.partydetail'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_party',
            field=models.ForeignKey(blank=True, limit_choices_to={'party_type': 'SHIP_TO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_invoices', to='nrcApp.partydetail'),
        ),
    ]
