# Generated by Django 5.1.2 on 2025-07-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrcApp', '0007_alter_invoice_bill_to_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Duration (in years)'),
        ),
    ]
