# Generated by Django 5.1.2 on 2025-07-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrcApp', '0008_alter_researchproject_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchProject',
        ),
    ]
