# Generated by Django 5.1.2 on 2024-12-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0024_rename_article_website_researchpub_article_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Name')),
                ('prog_cd', models.CharField(blank=True, max_length=20, null=True, verbose_name='Programme Code')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Programme/Courses Name')),
                ('acad_year', models.CharField(help_text='The range must be in  1990-91 to 2024-25.', max_length=7, verbose_name='Academic Year')),
                ('sanc_seats', models.IntegerField(verbose_name='Number of Sanctioned Seats')),
                ('admit_seats', models.IntegerField(verbose_name='Number of Admitted Students')),
                ('seats_resrv_catg', models.IntegerField(verbose_name='Number of Reserved Category Students')),
                ('group_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Group Table index')),
                ('prog_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.department', verbose_name='Programme Name')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Assigned Teacher')),
            ],
        ),
    ]
