# Generated by Django 5.1.2 on 2024-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmitted',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Programme/Courses Name'),
        ),
        migrations.AlterField(
            model_name='studentadmitted',
            name='reserv_catg',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('cast-1', 'SC'), ('cast-2', 'ST'), ('cast-3', 'OBC-A'), ('cast-4', 'OBC-B'), ('cast-5', 'GEN')], max_length=7, null=True, verbose_name='Reserved Category Students'),
        ),
    ]
