# Generated by Django 5.1.2 on 2025-03-23 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0001_initial'),
        ('teachers', '0025_patents_inv_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Name')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Programme/Courses Name')),
                ('prog_cd', models.CharField(blank=True, max_length=20, null=True, verbose_name='Programme Code')),
                ('enrol_year', models.IntegerField(verbose_name='Enrollment Year')),
                ('contact_hrs', models.IntegerField(verbose_name='Contact hours of the course')),
                ('enrol_students', models.IntegerField(verbose_name='Number of Students Enrolled')),
                ('complete_count', models.IntegerField(verbose_name='Number of Students completing the course')),
                ('group_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Group Table index')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Assigned Teacher')),
            ],
        ),
    ]
