# Generated by Django 5.1.2 on 2025-03-23 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0002_onlinecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentadmitted',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentadmitted',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
