# Generated by Django 5.1.2 on 2024-11-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0002_studentadmitted_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmitted',
            name='acad_year',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Academic Year'),
        ),
    ]
