# Generated by Django 5.1.2 on 2024-12-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0003_alter_studentadmitted_acad_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmitted',
            name='reserv_catg',
        ),
        migrations.AddField(
            model_name='studentadmitted',
            name='group_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Group Table index'),
        ),
    ]
