# Generated by Django 5.1.2 on 2025-03-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0003_onlinecourse_created_date_onlinecourse_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Upload Course Document'),
        ),
    ]
