# Generated by Django 5.1.2 on 2025-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0004_onlinecourse_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecourse',
            name='enrol_year',
            field=models.CharField(help_text='The range must be in  1990 onwards', max_length=4, verbose_name='Enrollment Year'),
        ),
    ]
