# Generated by Django 5.1.2 on 2024-12-02 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0004_remove_studentadmitted_reserv_catg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmitted',
            name='acad_year',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="Academic year must be in the format 'YYYY-YY', e.g., '2023-24'.", regex='^\\d{4}-\\d{2}$')], verbose_name='Academic Year'),
        ),
    ]
