# Generated by Django 5.1.2 on 2025-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0005_alter_onlinecourse_enrol_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecourse',
            name='contact_hrs',
            field=models.CharField(help_text='Reasonable range (e.g., 1 to 100)', max_length=4, verbose_name='Contact hours of the course'),
        ),
    ]
