# Generated by Django 5.1.2 on 2024-12-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0005_alter_studentadmitted_acad_year'),
        ('teachers', '0024_rename_article_website_researchpub_article_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmitted',
            name='admit_seats',
            field=models.IntegerField(verbose_name='Number of Admitted Students'),
        ),
        migrations.AlterField(
            model_name='studentadmitted',
            name='prog_name',
            field=models.ForeignKey(default=2007, on_delete=django.db.models.deletion.CASCADE, to='teachers.department', verbose_name='Programme Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentadmitted',
            name='sanc_seats',
            field=models.IntegerField(verbose_name='Number of Sanctioned Seats'),
        ),
        migrations.AlterField(
            model_name='studentadmitted',
            name='seats_resrv_catg',
            field=models.IntegerField(verbose_name='Number of Reserved Category Students'),
        ),
    ]
