# Generated by Django 5.1.2 on 2024-12-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0006_alter_studentadmitted_admit_seats_and_more'),
        ('teachers', '0024_rename_article_website_researchpub_article_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmitted',
            name='prog_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.department', verbose_name='Programme Name'),
        ),
    ]
