# Generated by Django 5.1.2 on 2025-03-29 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0006_alter_onlinecourse_contact_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
