# Generated by Django 5.1.2 on 2025-03-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0007_onlinecourse_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinecourse',
            name='verification_code',
        ),
    ]
