# Generated by Django 5.1.2 on 2024-12-06 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0007_alter_studentadmitted_prog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmitted',
            name='acad_year',
            field=models.CharField(default=1999, max_length=7, validators=[django.core.validators.RegexValidator(message="Academic year must be in the format 'YYYY-YY', e.g., '2023-24'.", regex='^\\d{4}-\\d{2}$')], verbose_name='Academic Year'),
            preserve_default=False,
        ),
    ]
