# Generated by Django 5.1.2 on 2024-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod_group', '0008_alter_studentadmitted_acad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmitted',
            name='acad_year',
            field=models.CharField(max_length=7, verbose_name='Academic Year'),
        ),
    ]
