# Generated by Django 5.1.2 on 2025-08-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('Arts', 'Arts'), ('Sc', 'Science'), ('Engg', 'Engineering'), ('ISLM', 'ISLM')], max_length=10)),
                ('name_hod', models.CharField(max_length=200)),
                ('contact_number_office', models.CharField(blank=True, max_length=20)),
                ('contact_number_hod', models.CharField(blank=True, max_length=20)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('academic_year', models.CharField(max_length=9)),
                ('spl_assistant_prog', models.BooleanField(default=False)),
                ('dept_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_audits', to='acad_audit.department')),
            ],
            options={
                'verbose_name': 'Academic Audit',
                'verbose_name_plural': 'Academic Audits',
                'unique_together': {('dept_school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SpecialAssistantProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_prog', models.CharField(max_length=255)),
                ('year_of_recognition', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=10)),
                ('academic_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_programs', to='acad_audit.academicaudit')),
            ],
        ),
    ]
