# Generated by Django 5.1.2 on 2025-08-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad_audit', '0001_initial'),
        ('teachers', '0025_patents_inv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicaudit',
            name='dept_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_audits', to='teachers.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
