# Generated by Django 5.1.2 on 2025-08-13 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad_audit', '0002_alter_academicaudit_dept_school_delete_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicaudit',
            options={},
        ),
        migrations.AlterField(
            model_name='academicaudit',
            name='academic_year',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Academic year must be in format YYYY–YY (e.g., 2024–25)', regex='^\\d{4}–\\d{2}$')]),
        ),
    ]
