# Generated by Django 5.1.2 on 2025-08-18 16:44

import acad_audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad_audit', '0003_alter_academicaudit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicaudit',
            name='academic_year',
            field=models.CharField(max_length=9, validators=[acad_audit.models.validate_academic_year]),
        ),
        migrations.AlterField(
            model_name='academicaudit',
            name='faculty',
            field=models.CharField(choices=[('ARTS', 'ARTS'), ('Sc', 'Science'), ('Engg', 'Engineering'), ('ISLM', 'ISLM')], max_length=10),
        ),
    ]
