# Generated by Django 5.1.2 on 2025-07-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0025_patents_inv_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Name')),
                ('pi_name', models.CharField(max_length=100, verbose_name='Name of the PI/Co-PI')),
                ('project_title', models.TextField(verbose_name='Title of the Research Project')),
                ('funding_agency', models.CharField(max_length=100, verbose_name='Name of the Funding Agency')),
                ('award_year', models.CharField(help_text='Format: YYYY-YY (e.g., 2018-19)', max_length=9, verbose_name='Year of Award or Sanction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount in Rs.')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration (in years)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Assigned Teacher')),
            ],
        ),
    ]
