# Generated by Django 5.1.2 on 2025-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataImport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Funding Agency'),
        ),
    ]
